# -*- coding: utf-8 -*-
"""SC_W8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17O_yaG1gLJTAOy6uoGDfsiptcee7s9Z7
"""

import numpy as np
ll=np.array([])
def sigmoid(value):
    return 1/1+np.exp(-value)

def perceptron():
    arr = np.array([list(map(float,input().split()))])
    size= np.shape(arr)
    weight=np.random.rand(1,size[1])
    bias = np.random.rand()
    value = (np.dot(arr,weight[0]))+bias
    ll=np.array([sigmoid(value)])

if __name__=='__main__':
    n=int(input("Enter number of perceptrons:"))
    for i in range(n):
        perceptron()
    print(l)